apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim
spec:
  storageClassName: my-example-pv # must match the PV above
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
