apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: tripplen63/todo-app:2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_PATH
              value: "/usr/src/app/files/image.jpg"
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-svc:2345"
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/files
