apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-output-config
      containers:
        - name: writer
          image: tripplen63/log-output:2.5
          imagePullPolicy: Always
          env:
            - name: ROLE
              value: "writer"
            - name: FILE_PATH
              value: "/usr/src/app/files/timestamp.txt"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: reader
          image: tripplen63/log-output:2.5
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ROLE
              value: "reader"
            - name: PORT
              value: "3000"
            - name: FILE_PATH
              value: "/usr/src/app/files/timestamp.txt"
            - name: PINGS_URL
              value: "http://ping-pong-svc:3000/pongs"
            - name: INFO_FILE
              value: "/usr/src/app/config/information.txt"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
            - name: config-volume
              mountPath: /usr/src/app/config
