apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller-account
      containers:
        - name: dummysite-controller
          image: dummysite-controller:5.1
          env:
            - name: SERVER_IMAGE
              value: dummysite-server:5.1