apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- ../../base
patches:
- path: deployment.yaml
images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/broadcaster
  newTag: 69a09d56d90453e947dfc90cafeb5edd8df5dee4
- name: PROJECT/CHAT-SINK
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/chat-sink
  newTag: 69a09d56d90453e947dfc90cafeb5edd8df5dee4
- name: PROJECT/TODO-APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/todo-app
  newTag: 69a09d56d90453e947dfc90cafeb5edd8df5dee4
- name: PROJECT/TODO-BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/todo-backend
  newTag: 69a09d56d90453e947dfc90cafeb5edd8df5dee4
