apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- ../../base
patches:
- path: deployment.yaml
images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/broadcaster
  newTag: 61c51ad8eb2e4104a7206680c5fd2e22bad5b735
- name: PROJECT/CHAT-SINK
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/chat-sink
  newTag: 61c51ad8eb2e4104a7206680c5fd2e22bad5b735
- name: PROJECT/TODO-APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/todo-app
  newTag: 61c51ad8eb2e4104a7206680c5fd2e22bad5b735
- name: PROJECT/TODO-BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-506208/my-repository/todo-backend
  newTag: 61c51ad8eb2e4104a7206680c5fd2e22bad5b735
